# Dockerfile pour MongoDB avec init-mongo.js
FROM mongo:7.0

# Copier le script d'initialisation
COPY init-mongo.js /docker-entrypoint-initdb.d/

# Exposer le port MongoDB
EXPOSE 27017

# Le script d'initialisation sera exécuté automatiquement au démarrage
