# Image de tests pour exécuter pytest dans un environnement stable
FROM python:3.13-slim

# Répertoire de travail
WORKDIR /app

# Copier uniquement ce qui est nécessaire pour les tests
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r /app/requirements.txt

# Copier les tests et scripts nécessaires
COPY test_bdd.py /app/
COPY test_readonly_security.py /app/
COPY test_readwrite_security.py /app/

# Par défaut, on exécute tous les tests
CMD ["pytest", "-s", "-vv"]
